#include <uti/clabel.h>
#define __CLASS_BODY__
#include <uti/stntype.h>
CLABEL STNTYPE RESET_PAT("RESET_PAT");
CLABEL STNTYPE __RESET_PAT("__RESET_PAT");
CLABEL STNTYPE TRIM_SCAN_C_addr1("TRIM_SCAN_C_addr1");
CLABEL STNTYPE R_TRIM_SCAN_C_addr("R_TRIM_SCAN_C_addr");
CLABEL STNTYPE R_TRIM_SCAN_C_addr1("R_TRIM_SCAN_C_addr1");
CLABEL STNTYPE TRIM_SCAN_C_data1("TRIM_SCAN_C_data1");
CLABEL STNTYPE R_TRIM_SCAN_C_data1("R_TRIM_SCAN_C_data1");
CLABEL STNTYPE TRIM_SCAN("TRIM_SCAN");
CLABEL STNTYPE __TRIM_SCAN("__TRIM_SCAN");
CLABEL STNTYPE R_TRIM_SCAN("R_TRIM_SCAN");
CLABEL STNTYPE __R_TRIM_SCAN("__R_TRIM_SCAN");
CLABEL STNTYPE R_0_a0x002("R_0_a0x002");
CLABEL STNTYPE __R_0_a0x002("__R_0_a0x002");
CLABEL STNTYPE H087("H087");
CLABEL STNTYPE __H087("__H087");
CLABEL STNTYPE H086("H086");
CLABEL STNTYPE __H086("__H086");
CLABEL STNTYPE H08C("H08C");
CLABEL STNTYPE __H08C("__H08C");
CLABEL STNTYPE H08B("H08B");
CLABEL STNTYPE __H08B("__H08B");
