#include <uti/clabel.h>
#include <uti/stntype.h>
CLABEL STNTYPE RESET_PAT;
CLABEL STNTYPE __RESET_PAT;
CLABEL STNTYPE TRIM_SCAN_C_addr1;
CLABEL STNTYPE R_TRIM_SCAN_C_addr;
CLABEL STNTYPE R_TRIM_SCAN_C_addr1;
CLABEL STNTYPE TRIM_SCAN_C_data1;
CLABEL STNTYPE R_TRIM_SCAN_C_data1;
CLABEL STNTYPE TRIM_SCAN;
CLABEL STNTYPE __TRIM_SCAN;
CLABEL STNTYPE R_TRIM_SCAN;
CLABEL STNTYPE __R_TRIM_SCAN;
CLABEL STNTYPE R_0_a0x002;
CLABEL STNTYPE __R_0_a0x002;
CLABEL STNTYPE H087;
CLABEL STNTYPE __H087;
CLABEL STNTYPE H086;
CLABEL STNTYPE __H086;
CLABEL STNTYPE H08C;
CLABEL STNTYPE __H08C;
CLABEL STNTYPE H08B;
CLABEL STNTYPE __H08B;
