#include <uti/category.h>
#include <uti/stntype.h>
CCATEGORY STNTYPE all_pass_0;
CCATEGORY STNTYPE hw_Open_short_test_0;
CCATEGORY STNTYPE hw_Leakage_test_0;
CCATEGORY STNTYPE hw_Trim_test_0;
CCATEGORY STNTYPE fail_last_item_0;
CCATEGORY STNTYPE hw_error_bin_0;
CCATEGORY STNTYPE SYS_ALARM_HW_BIN_0;
CCATEGORY STNTYPE SYS_ERROR_HW_BIN_0;
CCATEGORY STNTYPE all_pass_1;
CCATEGORY STNTYPE sw_OS_RESET_1;
CCATEGORY STNTYPE sw_V33_0p5V_Leakage_1;
CCATEGORY STNTYPE sw_V33_1V_Leakage_1;
CCATEGORY STNTYPE sw_VBG_TRIM_1;
CCATEGORY STNTYPE sw_VTC_TRIM_1;
CCATEGORY STNTYPE sw_VBG_a_TRIM_1;
CCATEGORY STNTYPE sw_VTC_a_TRIM_1;
CCATEGORY STNTYPE fail_last_item_1;
CCATEGORY STNTYPE hw_error_bin_1;
CCATEGORY STNTYPE SYS_ALARM_SW_BIN_1;
CCATEGORY STNTYPE SYS_ERROR_SW_BIN_1;
