#include <iostream>
#include <uti\cpin.h>
#include <uti\cpingrp.h>
#include <uti\ctimemain.h>
#include <uti\clevel.h>
#include <uti\clcdlevel.h>
#include <uti\alpgconst.h>
#define __CLASS_BODY__
#include <uti\stntype.h>
CPIN STNTYPE V33_dig("V33_dig");
CPIN STNTYPE NV5("NV5");
CPIN STNTYPE VDD_CH1("VDD_CH1");
CPIN STNTYPE VDD_CH2("VDD_CH2");
CPIN STNTYPE VDD_CH3("VDD_CH3");
CPIN STNTYPE VDD_CH4("VDD_CH4");
CPIN STNTYPE V33_1_4("V33_1_4");
CPIN STNTYPE V33_2("V33_2");
CPIN STNTYPE V33_3("V33_3");
CPIN STNTYPE TP_MLDPS("TP_MLDPS");
CPIN STNTYPE VFS_MLDPS("VFS_MLDPS");
CPIN STNTYPE RST("RST");
CPIN STNTYPE SDI("SDI");
CPIN STNTYPE SDO("SDO");
CPIN STNTYPE TRT("TRT");
CPIN STNTYPE TRR("TRR");
CPIN STNTYPE CS("CS");
CPIN STNTYPE EN_SET("EN_SET");
CPIN STNTYPE TP("TP");
CPIN STNTYPE VFS("VFS");
CPIN STNTYPE SCLKI("SCLKI");
CPIN STNTYPE SCLKO("SCLKO");
CPIN STNTYPE LD("LD");
CPINGRP STNTYPE MLDPS_ALLPINS("MLDPS_ALLPINS");
CPINGRP STNTYPE IO_ALLPINS("IO_ALLPINS");
CPINGRP STNTYPE os_pin("os_pin");
CPINGRP STNTYPE EFUSE_pin("EFUSE_pin");
CPINGRP STNTYPE RESET("RESET");
CPINGRP STNTYPE SD_IN("SD_IN");
CPINGRP STNTYPE SD_OUT("SD_OUT");
CPINGRP STNTYPE SCLK_IN("SCLK_IN");
CPINGRP STNTYPE SCLK_OUT("SCLK_OUT");
CPINGRP STNTYPE spi_pin("spi_pin");
CPINGRP STNTYPE NV50("NV50");
CPINGRP STNTYPE V33("V33");
CPINGRP STNTYPE DPS_allpin("DPS_allpin");
