#include <uti\cpin.h>
#include <uti\cpingrp.h>
#include <uti\ctimemain.h>
#include <uti\clevel.h>
#include <uti\clcdlevel.h>
#include <uti\alpgconst.h>
#include <uti\plnlib.h>
#include <uti\stntype.h>
/* PIN Declare */
CPIN STNTYPE V33_dig;
CPIN STNTYPE NV5;
CPIN STNTYPE VDD_CH1;
CPIN STNTYPE VDD_CH2;
CPIN STNTYPE VDD_CH3;
CPIN STNTYPE VDD_CH4;
CPIN STNTYPE V33_1_4;
CPIN STNTYPE V33_2;
CPIN STNTYPE V33_3;
CPIN STNTYPE TP_MLDPS;
CPIN STNTYPE VFS_MLDPS;
CPIN STNTYPE RST;
CPIN STNTYPE SDI;
CPIN STNTYPE SDO;
CPIN STNTYPE TRT;
CPIN STNTYPE TRR;
CPIN STNTYPE CS;
CPIN STNTYPE EN_SET;
CPIN STNTYPE TP;
CPIN STNTYPE VFS;
CPIN STNTYPE SCLKI;
CPIN STNTYPE SCLKO;
CPIN STNTYPE LD;

/*PINGROUP Declare*/
CPINGRP STNTYPE MLDPS_ALLPINS;
CPINGRP STNTYPE IO_ALLPINS;
CPINGRP STNTYPE os_pin;
CPINGRP STNTYPE EFUSE_pin;
CPINGRP STNTYPE RESET;
CPINGRP STNTYPE SD_IN;
CPINGRP STNTYPE SD_OUT;
CPINGRP STNTYPE SCLK_IN;
CPINGRP STNTYPE SCLK_OUT;
CPINGRP STNTYPE spi_pin;
CPINGRP STNTYPE NV50;
CPINGRP STNTYPE V33;
CPINGRP STNTYPE DPS_allpin;
